#!/usr/bin/env node

import * as fs from "node:fs/promises";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const docsDir = path.resolve(scriptDir, "../../../docs");
const outputPath = path.resolve(scriptDir, "../src/internal-urls/docs-index.generated.ts");

async function collectMarkdownFiles(dir: string, rootDir = dir): Promise<string[]> {
	const entries = await fs.readdir(dir, { withFileTypes: true });
	const files: string[] = [];

	for (const entry of entries) {
		const fullPath = path.join(dir, entry.name);
		if (entry.isDirectory()) {
			files.push(...(await collectMarkdownFiles(fullPath, rootDir)));
			continue;
		}

		if (entry.isFile() && entry.name.endsWith(".md")) {
			files.push(path.relative(rootDir, fullPath).split(path.sep).join("/"));
		}
	}

	return files;
}

const entries = await collectMarkdownFiles(docsDir);
entries.sort();

const docsWithContent = await Promise.all(
	entries.map(async relativePath => ({
		relativePath,
		content: await fs.readFile(path.join(docsDir, relativePath), "utf8"),
	})),
);

const filenamesLiteral = JSON.stringify(entries);

const mapEntries = docsWithContent
	.map(({ relativePath, content }) => `\t${JSON.stringify(relativePath)}: ${JSON.stringify(content)},`)
	.join("\n");
const output = [
	"// Auto-generated by scripts/generate-docs-index.ts - DO NOT EDIT",
	"",
	`export const EMBEDDED_DOC_FILENAMES: readonly string[] = ${filenamesLiteral};`,
	"",
	`export const EMBEDDED_DOCS: Readonly<Record<string, string>> = {`,
	`${mapEntries}`,
	`};`,
	"",
].join("\n");

await fs.mkdir(path.dirname(outputPath), { recursive: true });
await fs.writeFile(outputPath, output, "utf8");
console.log(`Generated ${path.relative(process.cwd(), outputPath)} (${entries.length} docs)`);
