#!/usr/bin/env node

import { execFileSync } from "node:child_process";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";
import tar from "tar-stream";

const GENERATED_FILE = path.join("src", "embedded-client.generated.txt");
const DIST_CLIENT_DIR = path.join("dist", "client");
const pnpmCommand = process.platform === "win32" ? "pnpm.cmd" : "pnpm";

function placeholderContent(): string {
	return `/**
 * Embedded stats dashboard bundle for compiled binaries.
 *
 * This file is generated by \`pnpm --dir packages/stats exec tsx scripts/generate-client-bundle.ts\` during
 * binary builds. The checked-in value is intentionally empty.
 */
export const EMBEDDED_CLIENT_ARCHIVE_TAR_GZ_BASE64 = "";
`;
}

async function collectFiles(dir: string): Promise<string[]> {
	const entries = await fs.readdir(dir, { withFileTypes: true });
	const files: string[] = [];
	for (const entry of entries) {
		const fullPath = path.join(dir, entry.name);
		if (entry.isDirectory()) {
			files.push(...(await collectFiles(fullPath)));
		} else if (entry.isFile()) {
			files.push(fullPath);
		}
	}
	files.sort((a, b) => a.localeCompare(b));
	return files;
}

async function buildArchiveBase64(dir: string): Promise<string> {
	const files = await collectFiles(dir);
	const pack = tar.pack();
	const chunks: Buffer[] = [];

	const archiveBufferPromise = new Promise<Buffer>((resolve, reject) => {
		pack.on("data", chunk => {
			chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
		});
		pack.on("end", () => resolve(Buffer.concat(chunks)));
		pack.on("error", reject);
	});

	for (const filePath of files) {
		const relativePath = path.relative(dir, filePath).split(path.sep).join("/");
		const content = await fs.readFile(filePath);
		await new Promise<void>((resolve, reject) => {
			pack.entry(
				{
					name: relativePath,
					size: content.length,
					mode: 0o644,
					mtime: new Date(0),
					uid: 0,
					gid: 0,
					uname: "",
					gname: "",
				},
				content,
				err => {
					if (err) {
						reject(err);
						return;
					}
					resolve();
				},
			);
		});
	}

	pack.finalize();
	const tarBuffer = await archiveBufferPromise;
	return gzipSync(tarBuffer, { level: 9 }).toString("base64");
}

async function main(): Promise<void> {
	const scriptDir = path.dirname(fileURLToPath(import.meta.url));
	const packageRoot = path.join(scriptDir, "..");
	const outputPath = path.join(packageRoot, GENERATED_FILE);

	if (process.argv.includes("--reset")) {
		await fs.writeFile(outputPath, placeholderContent(), "utf8");
		console.log(`Reset ${GENERATED_FILE}`);
		return;
	}

	execFileSync(pnpmCommand, ["run", "build"], { cwd: packageRoot, stdio: "inherit" });

	const archiveBase64 = await buildArchiveBase64(path.join(packageRoot, DIST_CLIENT_DIR));
	await fs.writeFile(outputPath, archiveBase64, "utf8");
	console.log(`Generated ${GENERATED_FILE}`);
}

await main();
